title: "Dashboard title"

header_links:
  - label: "Datenschutz"
    url: "https://www.zhaw.ch/de/datenschutz/"
  - label: "Rechtliche Hinweise"
    url: "https://www.zhaw.ch/de/rechtliche-hinweise/"

legal_notice:
  institution: "ZHAW Zurich University of Applied Sciences"
  unit:
    label: "Unit"       # leave blank to hide
    link_text: "Link to unit"   # optional: display text for the link
    link_url: "linktoun.it"    # optional: URL for the link
  department: "Department"
  institute: "Institute"
  contact: "Contact"
